name: Executar Pricebot 2026

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  executar-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar Bot
        run: python Bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID_POST: ${{ secrets.CHAT_ID_POST }}
          CHAT_ID_REPORT: ${{ secrets.CHAT_ID_REPORT }}
